// @ts-nocheck
// This file is autogenerated by scripts/registry-builder.ts
// Do not edit this file directly.
import * as React from "react";

export const Index: Record<string, any> = {
  alpha: {
    "tree-view-api": {
      name: "tree-view-api",
      type: "components:library",
      registryDependencies: undefined,
      component: React.lazy(
        () => import("@/components/tree-view/tree-view-api")
      ),
      files: ["src/registry/alpha/library/tree-view-api.tsx"],
    },
  },
};
