// @ts-nocheck
// This file is autogenerated by scripts/registry-builder.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
    "alpha": {
    "boop": {
      name: "boop",
      type: "components:library",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/alpha/library/boop.tsx")),
      files: ["src/registry/alpha/library/boop.tsx"],
    },
  },
}
