// @ts-nocheck
// This file is autogenerated by scripts/registry-builder.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
    "alpha": {
    "banner-content": {
      name: "banner-content",
      type: "components:library",
      registryDependencies: [],
      component: React.lazy(() => import("@/registry/alpha/library/banner/banner-content.tsx")),
      files: ["src/registry/alpha/library/banner/banner-content.tsx"],
    },
    "banner-shell": {
      name: "banner-shell",
      type: "components:library",
      registryDependencies: ["banner-content","banner-trigger"],
      component: React.lazy(() => import("@/registry/alpha/library/banner/banner-shell.tsx")),
      files: ["src/registry/alpha/library/banner/banner-shell.tsx"],
    },
    "banner-switch": {
      name: "banner-switch",
      type: "components:library",
      registryDependencies: ["switch-w-thumb"],
      component: React.lazy(() => import("@/registry/alpha/library/banner/banner-switch.tsx")),
      files: ["src/registry/alpha/library/banner/banner-switch.tsx"],
    },
    "banner-trigger": {
      name: "banner-trigger",
      type: "components:library",
      registryDependencies: [],
      component: React.lazy(() => import("@/registry/alpha/library/banner/banner-trigger.tsx")),
      files: ["src/registry/alpha/library/banner/banner-trigger.tsx"],
    },
    "bare-banner-trigger": {
      name: "bare-banner-trigger",
      type: "components:library",
      registryDependencies: [],
      component: React.lazy(() => import("@/registry/alpha/library/banner/bare-banner-trigger.tsx")),
      files: ["src/registry/alpha/library/banner/bare-banner-trigger.tsx"],
    },
    "switch-w-thumb": {
      name: "switch-w-thumb",
      type: "components:library",
      registryDependencies: [],
      component: React.lazy(() => import("@/registry/alpha/library/banner/switch-w-thumb.tsx")),
      files: ["src/registry/alpha/library/banner/switch-w-thumb.tsx"],
    },
    "trnsprncy-button": {
      name: "trnsprncy-button",
      type: "components:library",
      registryDependencies: ["banner-options"],
      component: React.lazy(() => import("@/registry/alpha/library/banner/trnsprncy-button.tsx")),
      files: ["src/registry/alpha/library/banner/trnsprncy-button.tsx"],
    },
    "categorized-options": {
      name: "categorized-options",
      type: "components:library",
      registryDependencies: ["banner-switch"],
      component: React.lazy(() => import("@/registry/alpha/library/banner/categorized-options.tsx")),
      files: ["src/registry/alpha/library/banner/categorized-options.tsx"],
    },
    "custom-banner": {
      name: "custom-banner",
      type: "components:demo",
      registryDependencies: ["banner-shell","banner-opts-base","trnsprncy-button","banner-triggers"],
      component: React.lazy(() => import("@/registry/alpha/demo/fake-banner-demo.tsx")),
      files: ["src/registry/alpha/demo/fake-banner-demo.tsx"],
    },
  },
}
